"""Initial Tracker Schema

Revision ID: 1167c16962a9
Revises: 
Create Date: 2026-06-19 00:09:30.626941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1167c16962a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('hr_contact', sa.String(), nullable=True),
    sa.Column('hiring_manager', sa.String(), nullable=True),
    sa.Column('technical_contact', sa.String(), nullable=True),
    sa.Column('ats_score', sa.String(), nullable=True),
    sa.Column('application_status', sa.String(), nullable=True),
    sa.Column('applied_date', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.String(), nullable=True),
    sa.Column('job_link', sa.String(), nullable=True),
    sa.Column('drafted_message', sa.String(), nullable=True),
    sa.Column('improvement_suggestions', sa.String(), nullable=True),
    sa.Column('resume_used', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
